<?
use Vivo\CMS\Model\Content\Fileboard;

$formType = DluTwBootstrap\Form\FormUtil::FORM_TYPE_HORIZONTAL;
if($form->get('gl-new')) {
    echo $this->formFieldsetTwb($form->get('gl-new'), $formType, array(), true, false);
}
?>
<? if($files) : ?>
    <div>
        <a href="<?=$this->actionUrl('deleteAll')?>">Smazat vše</a>
    </div>
    <ol>
        <?
         $count = count($files);
         foreach ($files as $i => $file) {
            //$u = $file->getUuid();
        ?>
            <li style="border:1px solid gray; margin:6px;">
                <img src="<?=$this->resource('resource.'.$file->getExt(), $file);?>" alt="" />
            </li>
        <? } ?>
    </ol>
<? endif; ?>