<?php
	foreach ($links as $link) {
	    $this->headLink()->append($link);
	}

	foreach ($scripts as $script) {
	    $this->headScript()->append($script);
	}
	?><?=$this->doctype($doctype);?>

	<head>

	<? foreach ($metas as $element): ?>
	<meta<? foreach ($element as $name => $value) echo " $name=\"".htmlspecialchars($value).'"' ?> />
	<? endforeach ?>

	<?= $this->headLink()?>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="<?= $this->resource('js/html5.js','Vivo')?>"></script>
    <![endif]-->

  </head>

  <body>

    <?=$main?>

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="js/jquery.js"></script>
    <script src="js/bootstrap.js"></script>

    <?= $this->headScript()?>

  </body>
</html>
