<?php
foreach ($links as $link) {
    $this->headLink()->append($link);
}

foreach ($scripts as $script) {
    $this->headScript()->append($script);
}
?><?=$this->doctype($doctype);?>

<head>

<? foreach ($metas as $element): ?>
<meta<? foreach ($element as $name => $value) echo " $name=\"".htmlspecialchars($value).'"' ?> />
<? endforeach ?>

<?= $this->headLink()?>

<?= $this->headScript()?>
</head>
<body>
<?=$main?>
</body>
</html>
