<table class="tableGrid light stripeMe">
    <thead>
        <tr>
            <th class="nowrap">
                <div>
                    <span class="title">#</span>
                </div>
            </th>
            <th class="nowrap">
                <div>
                    <span class="title"><?= $this->translate('Document name') ?></span>
                </div>
            </th>
            <th class="nowrap">
                <div>
                    <span class="title"><?= $this->translate('Document path') ?></span>
                </div>
            </th>
        </tr>
    </thead>
    <tbody>
        <? if (isset($parent)): ?>
            <tr>
                <td>
                    <div></div>
                </td>
                <td>
                    <div><?= $this->actionLink('set', '..', array($parent->getPath())) ?></div>
                </td>
                <td>
                    <div><?= $this->translate('parent folder') ?></div>
                </td>
            </tr>
        <? endif ?>
        <? $i = 0 ?>
        <? foreach ($documents as $document): ?>
            <tr>
                <td>
                    <div><?= ++$i ?></div>
                </td>
                <td>
                    <div><?= $this->actionLink('set', $document->getTitle(), array($document->getPath())) ?></div>
                </td>
                <td>
                    <div><?= $document->getPath() ?></div>
                </td>
            </tr>
        <? endforeach; ?>
    </tbody>
</table>
