<table class="table table-hover">
    <thead>
        <tr>
            <th>#</th>
            <th><?= $this->translate('Document name') ?></th>
            <th><?= $this->translate('Document path') ?></th>
        </tr>
    </thead>
    <tbody>
        <? if (isset($parent)): ?>
            <tr>
                <td></td>
                <td><?= $this->actionLink('set', '..', array($parent->getPath())) ?></td>
                <td><?= $this->translate('parent folder') ?></td>
            </tr>
        <? endif ?>
        <? $i = 0 ?>
        <? foreach ($documents as $document): ?>
            <tr>
                <td><?= ++$i ?></td>
                <td><?= $this->actionLink('set', $document->getTitle(), array($document->getPath())) ?></td>
                <td><?= $document->getPath() ?></td>
            </tr>
        <? endforeach; ?>
    </tbody>
</table>
