Editor<hr>
<form name="<?= $form->getName() ?>" action="<?=$form->getAttribute('action')?>" method="<?=$form->getAttribute('method')?>">
    <fieldset>
    <?
    foreach ($form->get('entity')->getElements() as $element) {
        echo $this->partial('Vivo\Backend\Form\Element', array('element'=>$element));
    }
    ?>
    </fieldset>
    <?=$contentTab?>
    <hr>
    <?=$this->formRow($form->get('act'))?>
    <?=$this->formRow($form->get('csrf'))?>
    <?=$this->vivoFormFieldset($form->get('buttons'))?>
</form>
Resource editor<hr>
<?=$resourceEditor?>
