<?php
    $formType       = \DluTwBootstrap\Form\FormUtil::FORM_TYPE_HORIZONTAL;
    //Display options
    $displayOptions = array(
        'fieldsets' => array(
            'entity'    => array(
                'elements'  => array(
                    'path'      => array(
                        'class' => 'span5',
                    ),
                ),
            ),
        ),
    );
?>
Editor<hr>
<?php
    echo $this->formTwb()->openTag($form, $formType);
    $fsEntity   = $form->get('entity');
    $doEntity = $displayOptions['fieldsets']['entity'];
    echo $this->formFieldsetTwb($fsEntity, $formType, $doEntity);
    echo $contentTab;
?>
<hr>
<?php
    echo $this->formRow($form->get('act'));
    echo $this->formRow($form->get('csrf'));
    echo $this->vivoFormFieldset($form->get('buttons'));
    echo $this->formTwb()->closeTag();
?>
Resource editor<hr>
<?
    echo $resourceEditor;
?>
