<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ApacheSolr\Module'                               => __DIR__ . '/Module.php',
    'ApacheSolr\Document'                             => __DIR__ . '/src/ApacheSolr/Document.php',
    'ApacheSolr\Exception'                            => __DIR__ . '/src/ApacheSolr/Exception.php',
    'ApacheSolr\HttpTransport\AbstractHttpTransport'  => __DIR__ . '/src/ApacheSolr/HttpTransport/AbstractHttpTransport.php',
    'ApacheSolr\HttpTransport\Curl'                   => __DIR__ . '/src/ApacheSolr/HttpTransport/Curl.php',
    'ApacheSolr\HttpTransport\CurlNoReuse'            => __DIR__ . '/src/ApacheSolr/HttpTransport/CurlNoReuse.php',
    'ApacheSolr\HttpTransport\FileGetContents'        => __DIR__ . '/src/ApacheSolr/HttpTransport/FileGetContents.php',
    'ApacheSolr\HttpTransport\HttpTransportInterface' => __DIR__ . '/src/ApacheSolr/HttpTransport/HttpTransportInterface.php',
    'ApacheSolr\HttpTransport\Response'               => __DIR__ . '/src/ApacheSolr/HttpTransport/Response.php',
    'ApacheSolr\HttpTransportException'               => __DIR__ . '/src/ApacheSolr/HttpTransportException.php',
    'ApacheSolr\InvalidArgumentException'             => __DIR__ . '/src/ApacheSolr/InvalidArgumentException.php',
    'ApacheSolr\NoServiceAvailableException'          => __DIR__ . '/src/ApacheSolr/NoServiceAvailableException.php',
    'ApacheSolr\ParserException'                      => __DIR__ . '/src/ApacheSolr/ParserException.php',
    'ApacheSolr\Response'                             => __DIR__ . '/src/ApacheSolr/Response.php',
    'ApacheSolr\Service\Balancer'                     => __DIR__ . '/src/ApacheSolr/Service/Balancer.php',
    'ApacheSolr\Service'                              => __DIR__ . '/src/ApacheSolr/Service.php',
);