<div id="loader">loading</div>
<div id="wrapper">

    <?=$headerBar ?>

    <div class="manager_panel">
        <?=$modulesPanel ?>
    </div>
    
    <div class="manager_content">
        <?=$module ?>
        <div class="clear"></div>
    </div>

    <div class="clear"></div>

    <div id="footer">
        <?=$footerBar ?>
    </div>
</div>
<noscript>
    <p class="noscript">Pro správné fungování je nutné mít zapnutý JavaScript!<br /><br />JavaScript must be enabled!</p>
</noscript>