<span class="site-name">SITENAME ...</span>
<ul id="availsites">
<?foreach($availableSites as $site):
$hosts = $site->getHosts();
?>
<?if (isset($selectedSite) && $selectedSite->getName() == $site->getName()):?>
<li class="active">
<?else:?>
<li>
<?endif;?>
<a href="<?=$this->url('backend/modules', array ('host' => current($hosts), 'path' => ''))?>"><?=$site->getName()?></a>
</li>
<?endforeach;?>
</ul>
