<?php
//$param = $viewAll ? '-all' : '';
$param = "";
?>
<div id="tabContainer<?=$param?>">
    <div id="tabs<?=$param?>">
        <div class="tabsHolder<?=$param?>">
            <ul class="tabs">
                <?
                $position = 0;
                foreach ($tabs as $tab):
                    $position++;
                ?>
                <li<?/*if ($tab['name'] == $selected):?> class="selected"<?endif*/?> data-rel="ribbon-tab-<?=$position?>">
                    <a href="#"><?=$this->translate($tab['label'])?></a>
                </li>
               <?endforeach?>
            </ul>
            <div class="clear"></div>
        </div>
    </div>
    <div class="clear"></div>

    <div class="tabContentRibbon">
        <?
        if (!empty($components))
            if ($viewAll) {
                $position   = 0;
                foreach ($components as $name):
                    $position++;
        ?>
                    <div id="ribbon-tab-<?=$position?>" class="tab-content">
                    <?php echo ${$name}; ?>
                    </div>
        <?php
                endforeach;
            } else {
                echo ${$selected};
            }?>
    </div>

</div>
<div class="clear"></div>
