<a href="<?=$this->actionUrl('logoff');?>" class="user-logout"><span>X</span></a>


<div class="user">
	<div class="user-icon">
		<?if ($user):?>
			<a href="" title="<?/*=$user->domain.'\\'.$user->username*/?>"><?/*=$user->fullname ? $user->fullname : $user->domain.'\\'.$user->username*/?><?=$user->getName();?></a>
		<?else:?>
			<?=$this->translate('Not logged in');?>
			<?/*=$this->vivoForm($form);*/?>
		<?endif?>
	</div>
</div>