<?
// example how to add css and js from template
//$this->headLink()->appendStylesheet('/.VivoSandboxModule.resource/css/Sample.css');
//$this->headScript()->appendFile('/.VivoSandboxModule.resource/js/DefinedInTemplate.js');
?>
<div class="samplediv">
<h4>LOGON UI COMPONENT</h4>
<?php
    /** @var $form \Vivo\Form\Logon */
    if ($form->getMessages()) {
        echo '<p>' . $this->escapeHtml($this->translate('Invalid input provided')) . '</p>';
    }
    //Add hidden field containing the required action
    $form->add(array(
        'name'          => 'act',
        'attributes'    => array(
            'type'          => 'hidden',
            'value'         => $this->action('logon'),
        ),
    ));
    echo $this->vivoForm($form);
    echo '<br>' . $this->actionLink('logoff', 'Logout');
?>
</div>
