<div class="OverviewDateDescThumb">

	<? if(count($children)) : ?>
		<ul class="thumbnails">
		<? foreach($children as $child) : ?>
			<li class="span9">
				<a class="thumbnail" href="<?=$this->document($child)?>">
					<div class="row-fluid">
						<div class="span3">
							<? if($child->getImage()) : ?>
							<img src="<?=$this->resource($child->getImage(), $child) ?>" alt="" />
							<? endif; ?>
						</div>
						<div class="span9 caption">
							<h3><?=$child->getTitle();?></h3>
							<? if ($child->getDescription()): ?>
							<p><?=$child->getPublished()->format('d.m.Y') ?></p>
							<p><?= htmlspecialchars($child->getDescription()); ?></p>
							<? endif; ?>
						</div>
					</div>
				</a>
			</li>
		<? endforeach; ?>
		</ul>
	<? endif; ?>

	<?/*
	<? if(count($children)) : ?>
		<ul class="thumbnails">
		<? foreach($children as $child) : ?>
			<li class="span3">
				<a class="thumbnail" href="<?=$this->document($child)?>">
					<div class="row-fluid">
						<? if($child->getImage()) : ?>
						<img src="<?=$this->resource($child->getImage(), $child) ?>" alt="" />
						<? endif; ?>
						<div class="span12 caption">
							<h3><?=$child->getTitle();?></h3>
							<? if ($child->getDescription()): ?>
							<p><?=$child->getPublished()->format('d.m.Y') ?></p>
							<p><?= htmlspecialchars($child->getDescription()); ?></p>
							<? endif; ?>
						</div>
					</div>
				</a>
			</li>
		<? endforeach; ?>
		</ul>
	<? endif; ?>
	*/?>
	</div>
</div>
