<div class="OverviewDateDescThumb">
<? if(count($children)) : ?>
	<ul>
	<? foreach($children as $child) : ?>
		<li class="clearfix">
			<? if($child->image) : ?>
				<img src="<?=$child->getURL().$child->image ?>?width=125&amp;height=81&amp;crop=1" alt="" />
			<? endif; ?>
			<a href="<?=$this->document($child)?>"><?=$child->getTitle();?></a><br />
            <?/*=$child->published->format('d.m.Y') */?>
            <? if ($child->getDescription()): ?>
            <p><?= htmlspecialchars($child->getDescription()); ?></p>
        	<? endif; ?>
        </li>
		<? endforeach; ?>
	</ul>
<? endif; ?>
</div>