<? if($files) : ?>
    <ul>
        <?
        foreach ($files as $file) {
            if($file instanceof Vivo\CMS\Model\Content\Fileboard\Media) {
                echo $this->partial('Vivo\CMS\UI\Content\Fileboard:Media',
                    array('model'=>$file));
            }
            else {
                echo $this->partial('Vivo\CMS\UI\Content\Fileboard:Separator',
                    array('model'=>$file, 'resource'=>$resources[$file->getUuid()]));
            }
        }
        ?>
    </ul>
<? endif; ?>