<? if($files) : ?>
    <ul>
        <? foreach ($files as $file) : /* @var $file \Vivo\CMS\Model\Content\Gallery\Media */
            $url = $this->resource('resource.'.$file->getExt(), $file);
            $size = $file->isLandscape()
                        ? min($this->info['image_thumbnail_width'], $this->info['image_thumbnail_height'])
                        : max($this->info['image_thumbnail_width'], $this->info['image_thumbnail_height']);
        ?>
            <li>
                <a href="<?=$url?>?width=<?=$this->info['image_preview_width']?>&amp;height=<?=$this->info['image_preview_height']?>&amp;quality=<?=$this->info['image_quality']?>">
                    <img src="<?=$url?>?size=<?=$size?>&amp;quality=<?=$this->info['image_quality']?>" alt="<?=htmlspecialchars($file->getName())?>" />
                </a>
                <p><?=htmlspecialchars($file->getDescription())?></p>
            </li>
        <? endforeach; ?>
    </ul>
<? endif; ?>