<?
$this->headLink()
  ->prependStylesheet('/.Vivo.resource/css/swiper/1.8.5/idangerous.swiper.css')
  ->prependStylesheet('/.Vivo.resource/css/front-Overview.CarouselTouch.css');

// $this->headScript()
//   ->appendFile('/.Vivo.resource/js/swiper/1.8.5/idangerous.swiper.js', $type = 'text/javascript', $attrs = array()) 
//   ->appendFile('/.Vivo.resource/js/front-Overview.CarouselTouch.js', $type = 'text/javascript', $attrs = array()); 
?>

<div class="OverviewCarouselTouch">
<!-- Carousel
================================================== -->
<? if(count($children)) : ?>
<div class="swiper-container">
  <div class="pagination"></div>
  <div class="swiper-wrapper">
    <? foreach($children as $key => $child) : ?>
    <div class="swiper-slide">
      <? if($child->getImage()) : ?>
        <img src="<?=$this->resource($child->getImage(), $child) ?>" alt="" />
      <? endif; ?>
        <div class="swiper-caption">
          <h3><?=$child->getTitle();?></h3>
          <? if ($child->getDescription()): ?>
            <p class="lead"><?= htmlspecialchars($child->getDescription()); ?></p>
          <? endif; ?>
          <a class="btn btn-large btn-primary" href="#">More</a>
        </div>
    </div>
    <? endforeach; ?>
  </div>
</div>
<? endif; ?>

</div>
