<?php
    $this->headScript()->appendFile('/.Vivo.resource/js/update-path.js');

    /** @var $entity \Vivo\CMS\Model\Entity */
    echo $this->escapeHtml($this->translate('Copy')) . ' ' . $this->escapeHtml($entity->getPath());
    $name   = $form->get('name');
    $name->setAttribute('onkeyup', 'this.form.name_in_path.value = updatePath(this.form.name_in_path.value, this.value)');
    echo $this->vivoForm($form);
?>
