    <div class="row-fluid">
        <div class="span12"><?=$finder ?></div>
    </div>

    <div class="row-fluid">
        <div class="span10">
            <div class="row-fluid">
                <div class="span12"><?=$ribbon ?></div>
            </div>
            <div class="row-fluid">
                <div class="span12"><?=$$currentName ?></div>
            </div>
        </div>
        <div class="span2">
        <?=$tree?>
        </div>
    </div>
