Ribbon

<a href="<?= $this->actionUrl('itemClick', array('browser'));?>">browser</a>
<a href="<?= $this->actionUrl('itemClick', array('viewer'));?>">viewer</a>
<a href="<?= $this->actionUrl('itemClick', array('editor'));?>">editor</a>
<a href="<?= $this->actionUrl('itemClick', array('delete'));?>">delete</a>
<a href="<?= $this->actionUrl('itemClick', array('copy'));?>">copy</a>
<a href="<?= $this->actionUrl('itemClick', array('move'));?>">move</a>
