<? if ($this->showPaginator) : ?>
<div class="paginator">
	<? if ($this->isFirst): ?>
		<span class="button">&laquo; <?= $this->translate('previous'); ?></span>
	<? else: ?>
		<a href="<?= $this->url(); ?>?<?= $this->prevPageQueryString; ?>">&laquo; <?= $this->translate('previous'); ?></a>


	<? endif; ?>

	<? foreach ($steps as $step => $queryString): ?>
	<? if ($lastStep && $lastStep + 1 < $step): ?>
		<span>&hellip;</span>
	<? endif; ?>
	<? if ($step == $this->page): ?>
		<span class="current"><?= $step ?></span>
	<? else: ?>
		<a href="<?= $this->url(); ?>?<?= $queryString; ?>"><?= $step ?></a>
	<? endif; ?>
	<? $lastStep = $step; ?>
	<? endforeach; ?>

	<? if ($this->isLast): ?>
		<span class="button"><?= $this->translate('next'); ?> &raquo;</span>
	<? else: ?>
		<a href="<?= $this->url(); ?>?<?= $this->nextPageQueryString ?>"><?= $this->translate('next'); ?> &raquo;</a>
	<? endif; ?>
</div>
<? endif; ?>
