<?php
    $formType = DluTwBootstrap\Form\FormUtil::FORM_TYPE_HORIZONTAL;
    //Display options
    $displayOptions = array(
        'fieldsets' => array(
            'entity'    => array(
                'elements'  => array(
                    'path'      => array(
                        'class' => 'input-block-level',
                    ),
                ),
            ),
        ),
    );
?>
<?php
    echo $this->formTwb()->openTag($form, $formType);
    $fsEntity   = $form->get('entity');
    $doEntity = $displayOptions['fieldsets']['entity'];
    echo $this->formFieldsetTwb($fsEntity, $formType, $doEntity);
    echo $contentTab;

    echo $this->formRowTwb($form->get('act'), $formType);
    echo $this->formRowTwb($form->get('csrf'), $formType);
    echo $this->formFieldsetTwb($form->get('buttons'), $formType);
    echo $this->formTwb()->closeTag();
?>
<?php if (isset($resourceEditor)): ?>
<hr>
<h3 id="resource-editor">Resource editor</h3>
<?php echo $resourceEditor; ?>
<?php endif ?>