 <div id="explorer">
	<div id="finder">
		<?=$finder ?>
	</div>
	<div class="explorer_tree">
		<div id="treeView">
			<div class="treeViewCont">
				<div class="treeViewContIn">
					<?=$tree?>
				</div>
			</div>
		</div>
	</div>
	<div class="explorer_tree_hitcher explorer_tree_hitcher_right_open explorer_tree_hitcher_right_closed">
		<div class="explorer_tree_hitcher_cont explorer_tree_hitcher_right_open"></div>
	</div>
	<div class="explorer_content explorer_content_with_tree">
		<div class="ribbon-holder" data-rel="<?/*= $this->getPath("viewOnlyRibbonHtml");*/ ?>" id="ribbonAction">
			<?=$ribbon ?>
		</div>
		<div class="tabMainContent">
			<div class="tabMainContentHolder">
			<?=$$explorerAction ?>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript"><!--
	window.finderGetPath = {
		'set':"<?/*= $this->finder->getPath('set') */?>",
		'renderSearchPulldown':"<?/*= $this->finder->getPath('renderSearchPulldown') */?>"
	};
//--></script>