<?
$is_published = true;
$id = "id_1";
?>
<div class="finderHolder">
    <form action="" method="post" id="<?= $id ?>" name="mainFinderMulti">

        <input type="hidden" name="getPath[getEntities]" value="main->param->param->finder->getEntities:9b4b6e3" />
        <input type="hidden" name="actionURL[set]" value="/system/manager/explorer/?act=main-%3Eparam-%3Eparam-%3Efinder-%3Eset%3A9b4b6e3" />
        <input type="hidden" name="finder[output]" value="main->param->param->finder->output:9b4b6e3" />
        <input type="hidden" name="getPath[viewBookmarks]" value="main->param->param->finder->viewBookmarks:9b4b6e3" />
        <input type="hidden" name="site[name]" value="Home" />
        <input type="hidden" name="getPath[getTitles]" value="main->param->param->finder->getTitles:9b4b6e3" />
        <input type="hidden" name="act" value="main-&gt;param-&gt;param-&gt;finder-&gt;set:9b4b6e3" />

        <table width="100%">
            <tr>
                <td class="path_root">&nbsp;<a><img src="<?= $this->resource('backend/img/icons/24x24/explorer.png','Vivo')?>" alt=""><? if ($is_published): ?><span class="published"></span><? endif; ?></a>&nbsp;</td>
                <td class="path_finder">
                    <div class="inputFinder">
                        <input type="text" name="input" autocomplete="off" value="/cs/" />
                        <input type="hidden" class="hidden" value="###CS" name="paths" />
                    </div>
                    <div class="inputFinderMulti" id="finderMulti_<?=$id?>"></div>
                </td>
            </tr>
        </table>
    </form>
</div>

<? /*
<div class="navbar">
    <div class="navbar-inner">
<form method="get" class="navbar-form pull-left">
<input type="hidden" name="act" value="<?=$this->action('set')?>">
<input type="text" name="args[]"/>
<input type="submit" class="btn" value="<?=$this->translate('Find');?>">
</form>
<div class="navbar-text span5" style="display: none"><b><?=$entity->getPath()?></b></div>
    </div>
</div>
*/ ?>