<?php
    $this->headScript()->appendFile('/.Vivo.resource/js/update-path.js');
?>
<h4>
    <?php
    /** @var $entity \Vivo\CMS\Model\Entity */
    echo $this->escapeHtml($this->translate('Move')) . ' ' . $this->escapeHtml($entityRelPath);
    ?>
</h4>
<?php
    $formType       = \DluTwBootstrap\Form\FormUtil::FORM_TYPE_HORIZONTAL;
    $name   = $form->get('name');
    $name->setAttribute('onkeyup', 'this.form.name_in_path.value = updatePath(this.form.name_in_path.value, this.value)');
    echo $this->formTwb($form, $formType);
?>
