<?
	$root = $tree->getChildrenNodes();
	$master_level = $tree->getDeep();

?>
<ul <?=($master_level != 0) ? "id=sub-".$tree->value['document']->getUuid() : "" ?>>
	<? $i = 0; ?>
	<? foreach ($root as $item): ?>
		<?
			$document = $item->value;

			$last = ($i == $tree->value['count'] - 1);
			$li_class = array();
			$cur_status = "normal";
			if ($document['expandable']) $li_class[] = $cur_status = $document['active_path'] ? "collapsable" : "expandable";
			if ($last) $li_class[] = ($document['expandable']) ? "last-".$cur_status : "last";
			if (($document['level'] == 1 && $i == 0)) $li_class[] = "root";
			if (!count($li_class)) $li_class[] = "normal";

			$title = $document['document']->getTitle();


		?>
		<li class="<?=implode(' ', $li_class);?>"  id="li-<?=$document['document']->getUuid();?>">
			<? if ($document['expandable'] && $document['level'] > 1): ?>
				<div class="hitarea <?=$cur_status?>-hitarea<?=($last) ? " last-$cur_status-hitarea" : ''?>" id="tree-<?=$document['document']->getUuid();?>" data-path="<?=$document['rel_path']?>"></div>
			<? endif; ?>

			<span class="<?=($document['expandable'])?'folder':'file'?>" id="cont-<?=$document['document']->getUuid();?>">
				<img src="<?= $this->iconUrl($document['document'])?>" alt="" />
					<? if ($document['published']): ?>
					<span class="published"></span>
					<? endif; ?>
				<a href="<?= htmlspecialchars($this->url('backend/explorer', array('path' => $document['document']->getUuid(), 'explorerAction' => $explorerAction))); ?>" class="<?=$cur_status?>-a<?=($document['active']) ? ' active' : ''?>" title="<?=$document['rel_path']?>">
					<?if ($document['document'] instanceof \Vivo\CMS\Model\Folder && ! $document['document'] instanceof \Vivo\CMS\Model\Document) :?>
						<span><b><?=htmlspecialchars($title)?></b></span>
					<?else:?>
						<span><?=htmlspecialchars($title)?></span>
					<?endif?>
				</a>
			</span>


			<? if ($item->getChildrenNodes()): ?>
				<?= $this->partial('Vivo\Backend\UI\Explorer\Tree:Subtree', array('tree' => $item, 'explorerAction' => $explorerAction)); ?>
			<? endif; ?>
		</li>
		<? $i++ ?>
	<? endforeach; ?>
	<? if ($i < $tree->value['count']): ?>
		<? $more = $tree->value['count'] - $i; ?>
		<li class="last">
			<span class="folder">
			<a href="<?= $this->actionUrl('showMore', array($document['parent_rel_path']))?>" class="more expandable-a"><span><?=$this->translate('more')?></span></a>
		</li>
	<? endif; ?>
</ul>
